/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    IMdiDiscord: typeof import('~icons/mdi/discord')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiGithubBox: typeof import('~icons/mdi/github-box')['default']
    IMdiYoutube: typeof import('~icons/mdi/youtube')['default']
    YoutubePlayer: typeof import('./src/components/YTPlayer/YoutubePlayer.vue')['default']
  }
}
